/*
  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  Implement a class `Todo` having below methods
    - add(todo): adds todo to list of todos
    - remove(indexOfTodo): remove todo from list of todos
    - update(index, updatedTodo): update todo at given index
    - getAll: returns all todos
    - get(indexOfTodo): returns todo at given index
    - clear: deletes all todos

  Once you've implemented the logic, test your code by running
  - `npm run test-todo-list`

  Create a todo Class in js
Each todo has a title and a description. The title is a string and the description is a string.
Each todo should also get an unique autogenerated id every time it is created
Don't use any database, just store all the data in an array to store the todo list data (in-memory) - may be todos[]

 Implement a class `Todo` having below methods
    - add(todo): adds todo to list of todos
    - remove(indexOfTodo): remove todo from list of todos
    - update(index, updatedTodo): update todo at given index
    - getAll: returns all todos
    - get(indexOfTodo): returns todo at given index
    - clear: deletes all todos
*/

class Todo {

    constructor(title, description) {
        this._id = 0;
        this.title = title;
        this.description = description;
    }
    //readonly id = this._id;
    add(todo) {
        todo.id = this.id; // <-- this line has been removed
        this._id++;
        this.todos.push(todo);
    }

    remove(indexOfTodo) {
        this.todos.splice(indexOfTodo, 1);
    }

    update(index, updatedTodo) {
        this.todos[index] = updatedTodo;
    }

    getAll() {
        return this.todos;
    }

    get(indexOfTodo) {
        return this.todos[indexOfTodo];
    }

    clear() {
        this.todos = [];
    }
}

const todo1 = new Todo("Buy groceries", "Milk, eggs, bread");
const todo2 = new Todo("Do laundry", "Wash, dry, fold");
const todo3 = new Todo("Walk the dog", "Around the block");

const todoList = [];
todoList.push(todo1);
todoList.push(todo2);
todoList.push(todo3);

console.log(todoList);
//console.log(todoList.getAll());



module.exports = Todo;
