name: Unit Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          cd 02-nodejs
          npm install 
          npm install jest express
          npx jest
